language: java
jdk:
  - oraclejdk8
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag v2.9.${TRAVIS_BUILD_NUMBER}
  - git push -q https://$GITHUB_KEY@github.com/NyaaCat/LockettePro HEAD:$TRAVIS_BRANCH --tags
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file:
    - build/libs/LockettePro-2.9.${TRAVIS_BUILD_NUMBER}-1.14.jar
  on:
    tags: false
  skip_cleanup: true
branches:
  only:
    - master